import {
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGIN_INVALID_CREDENTIALS,
} from "./login.constant";
import {
  EMPLOYEES_FETCH_SUCCESS,
  EMPLOYEES_FETCH_FAILURE,
} from "./employees.constant";

export {
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGIN_INVALID_CREDENTIALS,
  EMPLOYEES_FETCH_SUCCESS,
  EMPLOYEES_FETCH_FAILURE,
};
