const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_INVALID_CREDENTIALS = "LOGIN_INVALID_CREDENTIALS";
const LOGIN_FAILURE = "LOGIN_FAILURE";

export { LOGIN_SUCCESS, LOGIN_FAILURE, LOGIN_INVALID_CREDENTIALS };
